
# For full config options, check the docs:
#    docs.serverless.com
#
service: twitch-clip-worker

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10


# you can define service wide environment variables here
  environment: 
      TWITCHID: ${opt:twitchId}
      SERVICEDISCOVERY: ${opt:serviceDiscovery}
      STREAMER: ${opt:streamer} 

functions:
  checkClips:
    handler: handlers/twitchClips.check

